version: '3'

services: 
  api: 
    container_name: house-api
    # build: 
    #   context: ./API
    image: house-api
    restart: always
    depends_on:
      - bdd
    ports: 
      - '5000:5000'
    networks:
      - back-net

  bdd:
    container_name: house-bdd
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - ./API/database-data:/var/lib/mysql
    networks:
      - back-net

volumes:
  database-data:

networks:
  back-net:
